### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jantofw** [cdaecke/md_calendarize_frontend#3]
Tahnks for developing md_calendarize_frontend!
md_calendarize_frontend is dependent on calendarize (6.0.0 - 6.99.99).
I am using calendarize 9.0.0 because of typo3 10.4.15.
Will md_calendarize_frontend be ugraded for using with typo3 10.4.15?
Or is it safe to force the installation of md_calendarize_frontend?

**Comment by cdaecke** [comment]
Thanks for the hint!

I have just release a new version of the extension, which is compatible with `ext:calendarize` v9.

Have fun!
