### ISSUE TITLE
link "+ Datum hinzufügen" (add date) in frontend does not work

### ISSUE THREAD

**Issue by jantofw** [cdaecke/md_calendarize_frontend#5]
With

typo3 10.4.15
calendarize 9.0.0
md_calendarize_frontend 1.0.1
md_fullcalendar 2.0.2

the link "+ Datum hinzufügen" (add date) in frontend does not work (no visible reaction).

Firefox js-debugger says: Uncaught SyntaxError: missing : after property id
and points to this line:
var formElementCount = {elementCount + 1},

All other features work like a charm.

**Comment by cdaecke** [comment]
Thanks for reporting.

I have just pushed a bugfix. Is this working for you?

**Comment by jantofw** [comment]
As far as i can see only the file Resources/Private/Partials/Event/FormFieldsDate.html was changed. Right?
I copied it into my environment and tested the link, successfully.
Thanks for fast reacting!

**Comment by cdaecke** [comment]
Thanks for your feedback!

Version 1.0.2 is released.
