### ISSUE TITLE
TYPO3 V-12

### ISSUE THREAD

**Issue by Hasan-Shaker** [cdaecke/md_calendarize_frontend#8]
Hello,
Are you planning to upgrade to TYPO3 V-12?

**Comment by cdaecke** [comment]
Yes, this extension will be available for TYPO3 v12.

At the moment there is no official release of `lochmueller/calendarize` which supports TYPO3 v12, so I have to wait for this.

**Comment by Hasan-Shaker** [comment]
COOL
OK

**Comment by Hasan-Shaker** [comment]
Hello @cdaecke 
[ lochmueller/calendarize ](https://extensions.typo3.org/extension/calendarize) is official release for TYPO3 v12 now
😉

**Comment by cdaecke** [comment]
I have just added the TYPO3 v12 compatibility in the current master. Would be happy, if you could give it a try and test everything precisely.

**Comment by Hasan-Shaker** [comment]
Hello @cdaecke I'm going to test version 12

Thanks

**Comment by Hasan-Shaker** [comment]
Hello, I have Err 
TYPO3 V-12
PHP 8.2
The "Mediadreams\MdCalendarizeFrontend\Controller\EventController" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by cdaecke** [comment]
@Hasan-Shaker Did you upgrade from an older version of the extension?

I can't reproduce this error on a fresh TYPO3 v12 system with PHP 8.1.

**Comment by cdaecke** [comment]
@Hasan-Shaker Thanks for your pull request, which I have merged!

Is the current master now working for you?

**Comment by cdaecke** [comment]
Version 3.0.0 is released.
